// kSTEP PlaneGCS JNI bridge.
//
// A deliberately small, hand-written JNI shim around the vendored PlaneGCS 2D geometric constraint
// solver (third_party/planegcs/ -- see PROVENANCE.adoc and
// docs/adr/ADR-0006-planegcs-constraint-bridge.adoc for what is vendored, why, and under what
// license). Unlike kstep-geometry's OCCT bridge, this file does NOT link against a system-installed
// library -- the solver sources themselves are compiled directly into this shared object (see
// kstep-constraints/build.gradle.kts).
//
// Every exported function is `extern "C"` (JNI symbol resolution is by an exact,
// JNI-convention-mangled name computed from the *Java* declaring class and method name -- see the
// `Java_dev_kstep_constraints_planegcs_PlaneGcsBridge_*` names below, and note that `PlaneGcsBridge`
// is a plain Kotlin `object` without `@JvmStatic`/`companion object`, so every native method is an
// *instance* method taking a `jobject` second parameter -- verify with
// `nm -D --defined-only <library>.so` after any signature change here).
//
// Design note (see docs/adr/ADR-0006, "Decision"): this bridge is deliberately a ONE-SHOT,
// stateless API -- a single call builds a GCS::System on the stack, solves, writes the result back,
// and destroys everything on return. Unlike kstep-geometry's OcctBridge (which must keep a
// TopoDS_Shape* alive across multiple JNI calls via a handle registry + mutex, and had a
// use-after-free class of bug to fix as a result), there is no persistent native state here at all:
// no handle registry, no global mutable state, no mutex, nothing to leak via a forgotten close().
// An incremental/handle-based solver system is left to a later wave (ADR-0006, "Folge-Wellen").
//
// Two invariants hold throughout, mirroring kstep_occt_bridge.cpp:
//   1. No C++ exception ever crosses back across the JNI boundary. std::exception and a bare
//      `catch (...)` are both caught inside the one exported solving function and translated into a
//      Java exception via throwJava() before returning -- an uncaught C++ exception propagating out
//      of a JNI-called function is undefined behavior (typically process abort()).
//   2. Every argument is validated -- null-checked, then length-checked, then content-checked
//      (every coordinate finite, every constraint distance finite and positive, every fixedFlags
//      entry restricted to exactly 0 or 1), then constraint-index-range-checked -- BEFORE any
//      GCS::System is constructed or solved. PlaneGcsBridge is a public object precisely so
//      dev.kstep.tests.PlaneGcsBridgeSmokeTest can reach it directly with hostile input that
//      dev.kstep.constraints.PlaneGcsSolver's own Kotlin-side validation would normally reject; see
//      that Kotlin object's KDoc. Kotlin's compile-time non-null checks on `external fun` parameter
//      types do NOT run for a native method (no Kotlin-generated bytecode body carries the
//      Intrinsics.checkNotNullParameter guard), so a caller using java.lang.reflect.Method can
//      smuggle an actual null past a declared non-null Kotlin parameter type -- exactly the scenario
//      this file's null checks exist to make safe rather than undefined behavior. Content- and
//      index-range-checking exist for the same reason, one level down: PlaneGcsSolver's own
//      Kotlin-side `validate()` already rejects non-finite/out-of-range values before ever reaching
//      here, but this file must not simply assume that caller exists -- see the same KDoc.
//
// Security findings from reading the vendored solver source (see docs/adr/ADR-0006, "Security",
// for the full table) that this file's structure and the sibling Console.h shim exist to address:
//   - third_party/planegcs/GCS.cpp:283 and :2577 write GCS_debug.txt / subsystemfile.txt into the
//     process's current working directory, but ONLY when compiled with -D_DEBUG_TO_FILE or
//     -D_GCS_EXTRACT_SOLVER_SUBSYSTEM_ respectively. Neither macro is ever defined by
//     kstep-constraints/build.gradle.kts -- confirm with `grep _DEBUG_TO_FILE build.gradle.kts` if
//     that build file is ever touched.
//   - third_party/planegcs/GCS.cpp calls Console::Log(str.c_str()) with a RUNTIME string in the
//     format-string position in several places -- see Console.h's own header comment for why the
//     kSTEP-authored replacement never actually formats anything.
//   - GCS::System's constructor default is `debugMode(Minimal)`, NOT NoDebug (verified at
//     third_party/planegcs/GCS.cpp:484) -- this file sets it to GCS::NoDebug explicitly below,
//     rather than relying on the constructor default, so Console::Log is not reached in normal
//     operation at all (defense in depth on top of the Console.h shim itself).
#include <jni.h>

#include <cmath>
#include <exception>
#include <string>
#include <vector>

#include "GCS.h"

namespace {

/**
 * Throws a Java exception of the given class with the given message onto `env`. Does NOT unwind
 * the C++ call stack the way a C++ `throw` would -- the caller must still return immediately
 * afterward without touching any further JNI-observable state; the pending exception is only
 * delivered to the Java caller once the native function actually returns. Mirrors
 * kstep_occt_bridge.cpp's throwJava() exactly.
 */
void throwJava(JNIEnv* env, const char* className, const std::string& message) {
    jclass cls = env->FindClass(className);
    if (cls != nullptr) {
        env->ThrowNew(cls, message.c_str());
        env->DeleteLocalRef(cls);
    }
    // If FindClass itself failed, a pending exception (typically NoClassDefFoundError) is already
    // set on env by the JVM -- nothing further to do here.
}

/**
 * RAII wrapper around JNIEnv::GetDoubleArrayElements/ReleaseDoubleArrayElements. Always releases
 * with JNI_ABORT (discard any temporary copy, no write-back) -- this bridge only ever READS input
 * arrays through this guard; the one array it writes (outCoords) is filled via
 * SetDoubleArrayRegion instead, never via this guard, so there is never anything to write back.
 * `elements()` returns nullptr if the underlying array itself was nullptr, OR if the JVM reports an
 * OutOfMemoryError (in which case that error is already pending on `env`) -- the caller must check
 * for nullptr and return immediately in that case, exactly like every OCCT bridge OOM check.
 */
class DoubleArrayGuard {
public:
    DoubleArrayGuard(JNIEnv* env, jdoubleArray array) : env_(env), array_(array), elements_(nullptr) {
        if (array_ != nullptr) {
            elements_ = env_->GetDoubleArrayElements(array_, nullptr);
        }
    }
    ~DoubleArrayGuard() {
        if (elements_ != nullptr) {
            env_->ReleaseDoubleArrayElements(array_, elements_, JNI_ABORT);
        }
    }
    DoubleArrayGuard(const DoubleArrayGuard&) = delete;
    DoubleArrayGuard& operator=(const DoubleArrayGuard&) = delete;

    jdouble* elements() const { return elements_; }

private:
    JNIEnv* env_;
    jdoubleArray array_;
    jdouble* elements_;
};

/** Same as DoubleArrayGuard, for jintArray/GetIntArrayElements. */
class IntArrayGuard {
public:
    IntArrayGuard(JNIEnv* env, jintArray array) : env_(env), array_(array), elements_(nullptr) {
        if (array_ != nullptr) {
            elements_ = env_->GetIntArrayElements(array_, nullptr);
        }
    }
    ~IntArrayGuard() {
        if (elements_ != nullptr) {
            env_->ReleaseIntArrayElements(array_, elements_, JNI_ABORT);
        }
    }
    IntArrayGuard(const IntArrayGuard&) = delete;
    IntArrayGuard& operator=(const IntArrayGuard&) = delete;

    jint* elements() const { return elements_; }

private:
    JNIEnv* env_;
    jintArray array_;
    jint* elements_;
};

}  // namespace

extern "C" {

JNIEXPORT jstring JNICALL
Java_dev_kstep_constraints_planegcs_PlaneGcsBridge_nativePlaneGcsSourceCommit(JNIEnv* env, jobject /*self*/) {
    // KSTEP_PLANEGCS_COMMIT is supplied by kstep-constraints/build.gradle.kts as a -D compiler
    // define (see that file), pinned to the exact upstream commit vendored under
    // third_party/planegcs/ -- see PROVENANCE.adoc. This is the cheapest possible proof that the
    // JNI bridge actually loaded AND is built from the source tree this repository claims (checked
    // against ADR-0006/PROVENANCE.adoc by dev.kstep.tests.PlaneGcsBridgeSmokeTest).
#ifndef KSTEP_PLANEGCS_COMMIT
#error "KSTEP_PLANEGCS_COMMIT must be defined by the build (see kstep-constraints/build.gradle.kts)"
#endif
    try {
        return env->NewStringUTF(KSTEP_PLANEGCS_COMMIT);
    } catch (const std::exception& e) {
        throwJava(env, "java/lang/RuntimeException", std::string("Native error: ") + e.what());
    } catch (...) {
        throwJava(env, "java/lang/RuntimeException", "Unknown native error in nativePlaneGcsSourceCommit");
    }
    return nullptr;
}

// Kind values for constraintKinds -- MUST match dev.kstep.constraints.planegcs.NativeConstraintKind
// and PlaneGcsBridge.nativeSolveConstraints's KDoc table exactly. Three independent, hand-
// synchronized copies of the same contract (this file, that enum, and that KDoc table) -- see
// docs/adr/ADR-0007-planegcs-additional-constraint-types.adoc (kinds 0-4) and
// docs/adr/ADR-0014-planegcs-parallel-and-perpendicular.adoc (kinds 5-6) for the authoritative
// tables.
constexpr jint kKindP2PDistance = 0;
constexpr jint kKindP2PCoincident = 1;
constexpr jint kKindHorizontal = 2;
constexpr jint kKindVertical = 3;
constexpr jint kKindPointOnLine = 4;
constexpr jint kKindParallel = 5;
constexpr jint kKindPerpendicular = 6;

// Fixed number of point-index slots reserved per constraint in constraintPoints, regardless of a
// given kind's actual arity -- see PlaneGcsBridge.nativeSolveConstraints's KDoc and
// NativeConstraintKind.POINT_SLOTS for why 4 (not the current maximum arity of 3) was chosen.
constexpr jsize kPointSlotsPerConstraint = 4;
constexpr jint kUnusedPointSlot = -1;
constexpr jdouble kUnusedParam = 0.0;

JNIEXPORT jint JNICALL
Java_dev_kstep_constraints_planegcs_PlaneGcsBridge_nativeSolveConstraints(
    JNIEnv* env,
    jobject /*self*/,
    jdoubleArray coords,
    jintArray fixedFlags,
    jintArray constraintKinds,
    jintArray constraintPoints,
    jdoubleArray constraintParams,
    jint maxIterations,
    jdouble convergence,
    jdoubleArray outCoords) {
    // --- 1. Null checks, before ANY array access (see invariant 2 in the file header comment). ---
    if (coords == nullptr || fixedFlags == nullptr || constraintKinds == nullptr ||
        constraintPoints == nullptr || constraintParams == nullptr || outCoords == nullptr) {
        throwJava(env, "java/lang/NullPointerException", "nativeSolveConstraints: no array argument may be null");
        return -1;
    }

    // --- 2. Length checks, before any Get*ArrayElements call. All length arithmetic below is
    // divisionbased, never multiplication-based, to avoid a 32-bit jsize overflow on
    // kPointSlotsPerConstraint * constraintCount (see docs/adr/ADR-0007, "Overflow guard"). ---
    jsize coordsLen = env->GetArrayLength(coords);
    jsize fixedLen = env->GetArrayLength(fixedFlags);
    jsize kindsLen = env->GetArrayLength(constraintKinds);
    jsize cpLen = env->GetArrayLength(constraintPoints);
    jsize paramsLen = env->GetArrayLength(constraintParams);
    jsize outLen = env->GetArrayLength(outCoords);

    if (coordsLen < 0 || (coordsLen % 2) != 0) {
        throwJava(
            env, "java/lang/IllegalArgumentException", "coords length must be a non-negative even number (x,y pairs)");
        return -1;
    }
    jsize pointCount = coordsLen / 2;
    if (fixedLen != pointCount) {
        throwJava(
            env,
            "java/lang/IllegalArgumentException",
            "fixedFlags length must equal pointCount (coords.length / 2)");
        return -1;
    }
    if (outLen != coordsLen) {
        throwJava(env, "java/lang/IllegalArgumentException", "outCoords length must equal coords length");
        return -1;
    }
    if (paramsLen != kindsLen) {
        throwJava(
            env, "java/lang/IllegalArgumentException", "constraintParams length must equal constraintKinds length");
        return -1;
    }
    if (cpLen < 0 || (cpLen % kPointSlotsPerConstraint) != 0 || (cpLen / kPointSlotsPerConstraint) != kindsLen) {
        throwJava(
            env,
            "java/lang/IllegalArgumentException",
            "constraintPoints length must equal " + std::to_string(kPointSlotsPerConstraint) +
                " * constraintKinds length");
        return -1;
    }
    jsize constraintCount = kindsLen;
    if (maxIterations <= 0) {
        throwJava(env, "java/lang/IllegalArgumentException", "maxIterations must be positive");
        return -1;
    }
    if (!(convergence > 0.0) || std::isnan(convergence) || std::isinf(convergence)) {
        throwJava(env, "java/lang/IllegalArgumentException", "convergence must be a positive, finite number");
        return -1;
    }

    try {
        // --- 3. Pin input arrays (RAII; auto-released on every return path below). ---
        DoubleArrayGuard coordsGuard(env, coords);
        IntArrayGuard fixedGuard(env, fixedFlags);
        IntArrayGuard kindsGuard(env, constraintKinds);
        IntArrayGuard pointsGuard(env, constraintPoints);
        DoubleArrayGuard paramsGuard(env, constraintParams);

        if (coordsGuard.elements() == nullptr || fixedGuard.elements() == nullptr ||
            kindsGuard.elements() == nullptr || pointsGuard.elements() == nullptr ||
            paramsGuard.elements() == nullptr) {
            // OutOfMemoryError already pending on env, thrown by the JVM itself (Get*ArrayElements'
            // documented failure mode for a non-null array argument).
            return -1;
        }

        // --- 4. Content-check coords/fixedFlags BEFORE any value is used to build the solver's own
        // storage below -- see invariant 2 in the file header comment. Every loop here reads only
        // already-pinned arrays (no further Get*ArrayElements calls), so this stays cheap even at
        // MAX_POINTS/MAX_CONSTRAINTS. ---
        for (jsize i = 0; i < coordsLen; ++i) {
            if (!std::isfinite(coordsGuard.elements()[i])) {
                throwJava(
                    env,
                    "java/lang/IllegalArgumentException",
                    "coords[" + std::to_string(i) + "] must be finite, got " +
                        std::to_string(coordsGuard.elements()[i]));
                return -1;
            }
        }
        for (jsize i = 0; i < pointCount; ++i) {
            jint flag = fixedGuard.elements()[i];
            if (flag != 0 && flag != 1) {
                throwJava(
                    env,
                    "java/lang/IllegalArgumentException",
                    "fixedFlags[" + std::to_string(i) + "] must be 0 or 1, got " + std::to_string(flag));
                return -1;
            }
        }

        // --- 5. Per-constraint kind/slot/param/index validation, BEFORE any value is used to build
        // the solver's own storage below. Every kind's exact slot count (arity) and unused-slot/
        // unused-param sentinels are enforced here -- see PlaneGcsBridge.nativeSolveConstraints's
        // KDoc table. ---
        for (jsize i = 0; i < constraintCount; ++i) {
            jint kind = kindsGuard.elements()[i];
            int arity;
            switch (kind) {
                case kKindP2PDistance:
                case kKindP2PCoincident:
                case kKindHorizontal:
                case kKindVertical:
                    arity = 2;
                    break;
                case kKindPointOnLine:
                    arity = 3;
                    break;
                case kKindParallel:
                case kKindPerpendicular:
                    arity = 4;
                    break;
                default:
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraintKinds[" + std::to_string(i) + "] is not a recognized kind: " +
                            std::to_string(kind));
                    return -1;
            }

            jsize base = i * kPointSlotsPerConstraint;
            jint slotValues[kPointSlotsPerConstraint];
            for (jsize slot = 0; slot < kPointSlotsPerConstraint; ++slot) {
                jint value = pointsGuard.elements()[base + slot];
                slotValues[slot] = value;
                if (slot < arity) {
                    if (value < 0 || value >= pointCount) {
                        throwJava(
                            env,
                            "java/lang/IllegalArgumentException",
                            "constraintPoints[" + std::to_string(base + slot) +
                                "] is out of range for pointCount=" + std::to_string(pointCount) + ": " +
                                std::to_string(value));
                        return -1;
                    }
                } else if (value != kUnusedPointSlot) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraintPoints[" + std::to_string(base + slot) +
                            "] must be -1 for an unused slot on constraint kind " + std::to_string(kind) +
                            ", got " + std::to_string(value));
                    return -1;
                }
            }
            if (arity == 4) {
                // Parallel/Perpendicular (kind 5/6, see docs/adr/ADR-0014-planegcs-parallel-and-
                // perpendicular.adoc): each LEG ([0,1] = A, [2,3] = B) must individually be
                // non-degenerate, but the two legs ARE allowed to share an endpoint -- that is the
                // rectangle-corner/chamfer case (verified to solve correctly, see ADR-0014's T-C /
                // PlaneGcsConstraintTypesSmokeTest's T18). Full pairwise distinctness (the kinds
                // 0-4 rule below) would wrongly reject that case, so it is NOT applied here.
                if (slotValues[0] == slotValues[1]) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraint " + std::to_string(i) + " (kind " + std::to_string(kind) +
                            ") has a degenerate leg A: lineAFrom == lineATo (index " +
                            std::to_string(slotValues[0]) + ")");
                    return -1;
                }
                if (slotValues[2] == slotValues[3]) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraint " + std::to_string(i) + " (kind " + std::to_string(kind) +
                            ") has a degenerate leg B: lineBFrom == lineBTo (index " +
                            std::to_string(slotValues[2]) + ")");
                    return -1;
                }
                // Both legs naming the same unordered point pair is a second, distinct degeneracy:
                // Parallel becomes a constant-zero residual (trivially, permanently satisfied),
                // Perpendicular becomes a constant-positive residual (permanently unsatisfiable
                // except by collapsing the leg) -- see ParallelConstraint/PerpendicularConstraint's
                // KDoc. Reject both orderings (aFrom,aTo,bFrom,bTo) == (x,y,x,y) or (x,y,y,x).
                bool sameOrder = slotValues[0] == slotValues[2] && slotValues[1] == slotValues[3];
                bool swappedOrder = slotValues[0] == slotValues[3] && slotValues[1] == slotValues[2];
                if (sameOrder || swappedOrder) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraint " + std::to_string(i) + " (kind " + std::to_string(kind) +
                            ") references the same leg twice as lineA and lineB (indices [" +
                            std::to_string(slotValues[0]) + ", " + std::to_string(slotValues[1]) + "])");
                    return -1;
                }
                // Degenerate-leg COORDINATE check: PlaneGCS's Constraint::rescale() for both kinds
                // runs exactly once, in the constructor, from the leg's INITIAL coordinates (see
                // ADR-0014) -- a leg whose two points start at identical coordinates makes the
                // constraint's scale factor infinite and its residual permanently NaN for the
                // whole solve, silently inert rather than loudly failing. Rejected here, before any
                // GCS::System is built. Exact equality only, no epsilon -- see ADR-0014 for why.
                double aFromX = coordsGuard.elements()[2 * slotValues[0]];
                double aFromY = coordsGuard.elements()[2 * slotValues[0] + 1];
                double aToX = coordsGuard.elements()[2 * slotValues[1]];
                double aToY = coordsGuard.elements()[2 * slotValues[1] + 1];
                if (aFromX == aToX && aFromY == aToY) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraint " + std::to_string(i) + " (kind " + std::to_string(kind) +
                            ") has leg A starting at identical coordinates (indices " +
                            std::to_string(slotValues[0]) + "/" + std::to_string(slotValues[1]) + ")");
                    return -1;
                }
                double bFromX = coordsGuard.elements()[2 * slotValues[2]];
                double bFromY = coordsGuard.elements()[2 * slotValues[2] + 1];
                double bToX = coordsGuard.elements()[2 * slotValues[3]];
                double bToY = coordsGuard.elements()[2 * slotValues[3] + 1];
                if (bFromX == bToX && bFromY == bToY) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraint " + std::to_string(i) + " (kind " + std::to_string(kind) +
                            ") has leg B starting at identical coordinates (indices " +
                            std::to_string(slotValues[2]) + "/" + std::to_string(slotValues[3]) + ")");
                    return -1;
                }
            } else {
                // Pairwise-distinct check over exactly the used slots -- covers P2P/H/V's single
                // pair and PointOnLine's three-way distinctness (point/lineFrom/lineTo) with one
                // loop. NOT applied to kind 5/6 (arity 4) -- see the kind-aware block above.
                for (int a = 0; a < arity; ++a) {
                    for (int b = a + 1; b < arity; ++b) {
                        if (slotValues[a] == slotValues[b]) {
                            throwJava(
                                env,
                                "java/lang/IllegalArgumentException",
                                "constraint " + std::to_string(i) + " (kind " + std::to_string(kind) +
                                    ") references the same point twice (index " +
                                    std::to_string(slotValues[a]) + ")");
                            return -1;
                        }
                    }
                }
            }

            double param = paramsGuard.elements()[i];
            if (kind == kKindP2PDistance) {
                if (!std::isfinite(param) || !(param > 0.0)) {
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "constraintParams[" + std::to_string(i) + "] must be finite and positive for a distance " +
                            "constraint, got " + std::to_string(param));
                    return -1;
                }
            } else if (param != kUnusedParam) {
                // -0.0 == 0.0 is true in both C++ and Kotlin, so -0.0 passes this check -- accepted
                // deliberately, see docs/adr/ADR-0007's "Stolperfallen".
                throwJava(
                    env,
                    "java/lang/IllegalArgumentException",
                    "constraintParams[" + std::to_string(i) + "] must be 0.0 for a parameterless constraint " +
                        "kind " + std::to_string(kind) + ", got " + std::to_string(param));
                return -1;
            }
        }

        // --- 6. Build the solver's own storage.
        //
        // MOST IMPORTANT STOLPERFALLE OF THIS FILE (see docs/adr/ADR-0006, "Stolperfallen"):
        // GCS::Point holds a raw `double*` into these vectors (see third_party/planegcs/Geo.h), and
        // GCS::System::plist/pdrivenlist store more raw double* pointers of their own, all pointing
        // into the SAME backing storage. `params` and `distances` below are therefore constructed
        // ONCE, at their final size, and NEVER resized/push_back'd afterward -- any reallocation
        // would leave every GCS::Point (and the solver's own internal parameter list) holding a
        // dangling pointer into freed memory. Copying the JNI-pinned input arrays into these
        // independent std::vectors (rather than pointing GCS::Point directly at the JNI-pinned
        // `jdouble*` buffers) also means this bridge never depends on whatever
        // GetDoubleArrayElements chose to hand back (a direct pointer into the JVM heap, or a
        // temporary copy) outliving the JNI call -- once these vectors are built, the JNI-pinned
        // buffers are no longer touched at all. `distances` is sized to constraintCount (one slot
        // per constraint, including parameterless kinds that never use it) -- constant, allocated
        // once, never push_back'd, same invariant.
        std::vector<double> params(coordsLen);
        for (jsize i = 0; i < coordsLen; ++i) {
            params[i] = coordsGuard.elements()[i];
        }
        std::vector<double> distances(constraintCount);
        for (jsize i = 0; i < constraintCount; ++i) {
            distances[i] = paramsGuard.elements()[i];
        }

        std::vector<GCS::Point> points;
        points.reserve(pointCount);
        for (jsize i = 0; i < pointCount; ++i) {
            points.emplace_back(&params[2 * i], &params[2 * i + 1]);
        }

        GCS::System system;
        // GCS::System's constructor default is debugMode(Minimal), NOT NoDebug (verified at
        // third_party/planegcs/GCS.cpp:484) -- set explicitly rather than relying on that default,
        // so Console::Log is never reached in normal operation (see Console.h and the file header
        // comment above).
        system.debugMode = GCS::NoDebug;
        // DoS guard: caller-supplied bounds, additionally capped Kotlin-side by
        // PlaneGcsSolver.MAX_ITERATIONS -- this native function trusts its caller's bounds (already
        // range-checked above: maxIterations > 0, convergence finite and positive) but applies no
        // additional cap of its own; the hard ceiling lives in PlaneGcsSolver.solve, which is the
        // only intended caller other than this module's own tests. Point count
        // (PlaneGcsSolver.MAX_POINTS), not this iteration budget, is the primary lever that actually
        // bounds this call's wall time -- see that constant's KDoc for the measurements behind that
        // conclusion. sketchSizeMultiplier is deliberately left at its GCS::System() default
        // (false) -- if it were true, the solver's effective iteration budget would become maxIter
        // multiplied by the system's parameter count, making this cap far less predictable.
        system.maxIter = maxIterations;
        system.convergence = convergence;

        // --- 7. Reject pointCount == 0 and an all-fixed system natively too, not just Kotlin-side
        // (see docs/adr/ADR-0007, "Native hardening"): PlaneGcsSolver.solve already excludes both,
        // but PlaneGcsBridge is public so a direct (test) caller must get a defined result here too,
        // rather than relying on a well-behaved Kotlin caller. ---
        if (pointCount == 0) {
            throwJava(env, "java/lang/IllegalArgumentException", "pointCount must be positive");
            return -1;
        }

        GCS::VEC_pD unknowns;
        for (jsize i = 0; i < pointCount; ++i) {
            if (fixedGuard.elements()[i] == 0) {
                unknowns.push_back(&params[2 * i]);
                unknowns.push_back(&params[2 * i + 1]);
            }
        }
        if (unknowns.empty()) {
            throwJava(
                env,
                "java/lang/IllegalArgumentException",
                "at least one point must be non-fixed (an all-fixed system has no unknowns)");
            return -1;
        }

        for (jsize i = 0; i < constraintCount; ++i) {
            jint kind = kindsGuard.elements()[i];
            jsize base = i * kPointSlotsPerConstraint;
            // tagId must be non-zero and is otherwise only used by PlaneGCS for later
            // selective-clear/diagnosis operations this one-shot bridge never performs -- 1-based
            // constraint index is an arbitrary but stable choice.
            int tagId = static_cast<int>(i) + 1;
            switch (kind) {
                case kKindP2PDistance: {
                    jint a = pointsGuard.elements()[base];
                    jint b = pointsGuard.elements()[base + 1];
                    system.addConstraintP2PDistance(points[a], points[b], &distances[i], tagId);
                    break;
                }
                case kKindP2PCoincident: {
                    jint a = pointsGuard.elements()[base];
                    jint b = pointsGuard.elements()[base + 1];
                    system.addConstraintP2PCoincident(points[a], points[b], tagId);
                    break;
                }
                case kKindHorizontal: {
                    jint a = pointsGuard.elements()[base];
                    jint b = pointsGuard.elements()[base + 1];
                    system.addConstraintHorizontal(points[a], points[b], tagId);
                    break;
                }
                case kKindVertical: {
                    jint a = pointsGuard.elements()[base];
                    jint b = pointsGuard.elements()[base + 1];
                    system.addConstraintVertical(points[a], points[b], tagId);
                    break;
                }
                case kKindPointOnLine: {
                    jint p = pointsGuard.elements()[base];
                    jint lp1 = pointsGuard.elements()[base + 1];
                    jint lp2 = pointsGuard.elements()[base + 2];
                    system.addConstraintPointOnLine(points[p], points[lp1], points[lp2], tagId);
                    break;
                }
                case kKindParallel: {
                    jint a1 = pointsGuard.elements()[base];
                    jint a2 = pointsGuard.elements()[base + 1];
                    jint b1 = pointsGuard.elements()[base + 2];
                    jint b2 = pointsGuard.elements()[base + 3];
                    // PlaneGCS offers NO Point-quadruple overload of addConstraintParallel
                    // (GCS.h:296) -- only (Line&, Line&). These two GCS::Line values are therefore
                    // built here, on the stack, purely to satisfy that signature, and are destroyed
                    // at the end of this scope (right after addConstraintParallel returns). That is
                    // safe and verified, not assumed: ConstraintParallel's constructor
                    // (third_party/planegcs/Constraints.cpp:1178-1190) copies ONLY the eight raw
                    // double* out of l1/l2 into its own pvec, and System::addConstraint
                    // (GCS.cpp:557-573) stores only the Constraint* and those same double*s --
                    // neither retains the Line or its Points. Those double*s point into `params`,
                    // which outlives this entire solve and is never resized (see the "Build the
                    // solver's own storage" comment above). Regression-guarded by
                    // PlaneGcsConstraintTypesSmokeTest's T15/T16, which solve correctly with the
                    // Line long since out of scope. This is exactly why no Kotlin-side Line concept
                    // was introduced -- see docs/adr/ADR-0014-planegcs-parallel-and-perpendicular.adoc.
                    GCS::Line lineA;
                    lineA.p1 = points[a1];
                    lineA.p2 = points[a2];
                    GCS::Line lineB;
                    lineB.p1 = points[b1];
                    lineB.p2 = points[b2];
                    system.addConstraintParallel(lineA, lineB, tagId);
                    break;
                }
                case kKindPerpendicular: {
                    jint a1 = pointsGuard.elements()[base];
                    jint a2 = pointsGuard.elements()[base + 1];
                    jint b1 = pointsGuard.elements()[base + 2];
                    jint b2 = pointsGuard.elements()[base + 3];
                    // Perpendicular, unlike Parallel, has a native four-Point overload
                    // (GCS.h:298-303) -- no temporary GCS::Line needed.
                    system.addConstraintPerpendicular(points[a1], points[a2], points[b1], points[b2], tagId);
                    break;
                }
                default:
                    // Unreachable: already rejected in the validation pass above. Kept as a defensive
                    // guard rather than assumed unreachable, mirroring this file's own stated
                    // philosophy (see the file header comment).
                    throwJava(
                        env,
                        "java/lang/IllegalArgumentException",
                        "unreachable: unrecognized constraint kind " + std::to_string(kind) + " at index " +
                            std::to_string(i));
                    return -1;
            }
        }

        system.declareUnknowns(unknowns);
        system.initSolution();
        int status = system.solve();
        // applySolution() only on Success/Converged, matching the verified behavior of a conflicting
        // system (docs/adr/ADR-0006 "Environment note": a Failed solve still leaves the
        // last-attempted values in `params` via the solve loop itself, which is what outCoords below
        // reports either way -- applySolution() itself is solely about writing the *driven*
        // parameters' final values back for constraints created with driving=false, none of which
        // this bridge ever creates, so calling it unconditionally would be harmless here too, but
        // gating it on success mirrors PlaneGCS's own intended usage pattern more closely).
        if (status == GCS::Success || status == GCS::Converged) {
            system.applySolution();
        }

        // --- 8. Defense-in-depth: sweep `params` for a non-finite value before writing it back.
        // PlaneGcsSolver.solve performs the authoritative version of this check Kotlin-side (see its
        // KDoc and PointOnLineConstraint's KDoc for the ConstraintPointOnLine division-by-near-zero
        // hazard this guards against); this native sweep exists only for a caller that reaches
        // PlaneGcsBridge directly, and intentionally does NOT change the returned status -- it is
        // not authoritative, just defense in depth (see docs/adr/ADR-0007). ---
        for (jsize i = 0; i < coordsLen; ++i) {
            if (!std::isfinite(params[i])) {
                throwJava(
                    env,
                    "java/lang/RuntimeException",
                    "PlaneGCS produced a non-finite result at params[" + std::to_string(i) + "]");
                return -1;
            }
        }

        // --- 9. Write the result back via SetDoubleArrayRegion -- never via Get/ReleaseArrayElements
        // for outCoords, so there is no write-back array to release on any path above. ---
        env->SetDoubleArrayRegion(outCoords, 0, coordsLen, params.data());
        if (env->ExceptionCheck()) {
            // SetDoubleArrayRegion itself throws ArrayIndexOutOfBoundsException on a length
            // mismatch -- already excluded above by the outLen check, but defensive regardless of
            // that earlier check ever becoming stale.
            return -1;
        }

        return static_cast<jint>(status);
        // coordsGuard/fixedGuard/kindsGuard/pointsGuard/paramsGuard are released here via their
        // destructors, in reverse declaration order, regardless of which return path was taken above.
    } catch (const std::exception& e) {
        throwJava(env, "java/lang/RuntimeException", std::string("PlaneGCS native error: ") + e.what());
    } catch (...) {
        throwJava(env, "java/lang/RuntimeException", "Unknown native error in nativeSolveConstraints");
    }
    return -1;
}

}  // extern "C"
